---
- hosts: jitsi
  tasks:

    - name: Install pip3
      apt: name=python3-pip state=present 

    - name: Pip install Docker SDK for Python and docker-compose
      pip:
        name:
          - docker
          - docker-compose

    - name: deploy Docker Compose
      docker_compose:
        project_src: /home/docker-jitsi-meet
        files:
          - docker-compose.yml
