---
- hosts: jitsi
  gather_facts: false
  tasks:

  - name: Install docker packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker

  - name: Add Docker s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker

  - name: Verify that we have the key with the fingerprint
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker

  - name: Add docker repository to apt
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
      update_cache: true
    tags:
      - docker

  - name: Update apt and install docker-ce
    package:
      name: docker-ce
      state: present
    tags:
      - docker

  - name: Add remote "root" user to "docker" group
    user:
      name: "root"
      group: "docker"
      append: true
    tags:
      - docker

  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
