---
- hosts: jitsi
  become: true
  tasks:

  - name: Docker-compose build
    shell:
      cmd: docker-compose build
      chdir: /home/docker-jitsi-meet/

  - name: Docker-compose UP
    shell:
      cmd: "docker-compose up -d"
      chdir: /home/docker-jitsi-meet/

  - name: Create Portainer container
    docker_container:
      name: portainer
      image: portainer/portainer-ce
      state: started
      recreate: true
      restart_policy: always
      published_ports:
        - "8000:8000"
        - "9000:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

  - name: Creates directory /home/logo/
    become: true
    file:
      path: /home/logo/
      state: directory

  - name: Download quersystem logo.png
    become: true
    get_url:
      url: https://quersystem.com/wp-content/uploads/2021/02/quersystem-logo.png
      dest: /home/logo/watermark.png

  - name: Copy file into existing container at docker-jitsi-meet_web_1:/usr/share/jitsi-meet/images/watermark.png
    shell: docker cp /home/logo/watermark.png docker-jitsi-meet_web_1:/usr/share/jitsi-meet/images/watermark.png

  - name: Enter into a running container "docker-jitsi-meet_prosody_1" and run a command
    command: docker exec docker-jitsi-meet_prosody_1 prosodyctl --config /config/prosody.cfg.lua register Oleg meet.jitsi QUERSYSTEM777
