---
- hosts: jitsi
  become: true
  tasks:
  vars:
    - image_v1: '--filter ancestor=my_image:v1'
    - image_v2: '--filter ancestor=my_image:v2'
    - image_v3: '--filter ancestor=my_image:v3'
    - image_v4: '--filter ancestor=my_image:v4'
    - image_v5: '--filter ancestor=my_image:v5'

    - name: Get images name
      command: docker container ls -a {{ image_v1 }} {{ image_v2 }} --format "{{ '{{' }}.Names {{ '}}' }} {{ '{{' }}.Image {{ '}}' }}"
      register: docker_images

    - name: Restart images
      docker_container:
        name: "{{ item.split(' ')[0]}}"
        image: "{{ item.split(' ')[5]}}"
        state: started
        restart: true
      loop: "{{ docker_images.stdout_lines}}"
  