---
- hosts: VideoBridges #185.188.183.74
  become: true
  tasks:
  
  - name: Creates directory /home/VideoBridges/
    file:
      path: /home/VideoBridges/
      state: directory	
  
  - name: Creating a file with configuration 
    copy:
      dest: "/home/VideoBridges/docker-compose.yml"
      content: |
         version: '3'
         
         services:
             # Video bridge
             jvb2:
                 #image: jitsi/jvb:latest
                 build: ./jvb
                 restart: ${RESTART_POLICY}
                 ports:
                     - '${JVB_PORT}:${JVB_PORT}/udp'
                     - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
                 volumes:
                     - ${CONFIG}/jvb:/config:Z
                 environment:
                     - DOCKER_HOST_ADDRESS
                     - XMPP_AUTH_DOMAIN
                     - XMPP_INTERNAL_MUC_DOMAIN
                     - XMPP_SERVER
                     - JVB_AUTH_USER
                     - JVB_AUTH_PASSWORD
                     - JVB_BREWERY_MUC
                     - JVB_PORT
                     - JVB_TCP_HARVESTER_DISABLED
                     - JVB_TCP_PORT
                     - JVB_TCP_MAPPED_PORT
                     - JVB_STUN_SERVERS
                     - JVB_ENABLE_APIS
                     - JVB_WS_DOMAIN
                     - JVB_WS_SERVER_ID
                     - PUBLIC_URL
                     - TZ
                 #depends_on:
                 #    - prosody
                 networks:
                     meet.jitsi:
                         aliases:
                             - ${JVB_AUTH_USER}.${XMPP_DOMAIN}
                 extra_hosts:
                     - "xmpp.meet.jitsi:185.139.68.189"
