---
- hosts: Jitsi_Stack
  tasks:

    - name: backup file docker-compose.yml
      shell: cp /home/docker-jitsi-meet/docker-compose.yml /home/docker-jitsi-meet/docker-compose.yml.old
      when: inventory_hostname == "videobridge"

    - name: Remove file docker-compose.yml
      file:
        path: /home/docker-jitsi-meet/docker-compose.yml
        state: absent
      when: inventory_hostname == "videobridge"

    - name: Creating a new file docker-compose.yml with content
      copy:
        dest: "/home/docker-jitsi-meet/docker-compose.yml"
        content: |
            version: '3'

            services:
                # Video bridge
                jvb2:
                    #image: jitsi/jvb:stable-5870
                    build: ./jvb
                    restart: ${RESTART_POLICY}
                    ports:
                        - '${JVB_PORT}:${JVB_PORT}/udp'
                        - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
                    volumes:
                        - ${CONFIG}/jvb:/config:Z
                    environment:
                        - ENABLE_COLIBRI_WEBSOCKET
                        - ENABLE_OCTO
                        - DOCKER_HOST_ADDRESS
                        - XMPP_AUTH_DOMAIN
                        - XMPP_INTERNAL_MUC_DOMAIN
                        - XMPP_SERVER
                        - JVB_AUTH_USER
                        - JVB_AUTH_PASSWORD
                        - JVB_BREWERY_MUC
                        - JVB_PORT
                        - JVB_TCP_HARVESTER_DISABLED
                        - JVB_TCP_PORT
                        - JVB_TCP_MAPPED_PORT
                        - JVB_STUN_SERVERS
                        - JVB_ENABLE_APIS
                        - JVB_WS_DOMAIN
                        - JVB_WS_SERVER_ID
                        - PUBLIC_URL
                        - JVB_OCTO_BIND_ADDRESS
                        - JVB_OCTO_PUBLIC_ADDRESS
                        - JVB_OCTO_BIND_PORT
                        - JVB_OCTO_REGION
                        - TZ
                    #depends_on:
                    #    - prosody
                    networks:
                        meet.jitsi:
                            aliases:
                                - ${JVB_AUTH_USER}.${XMPP_DOMAIN}
                    extra_hosts:
                      - "xmpp.meet.jitsi:185.139.68.189"
      when: inventory_hostname == "videobridge"
