---
- hosts: Jitsi_Stack
  gather_facts: yes
  tasks:

    - name: Here we are displaying the inventory_hostname values.
      debug:
         msg: "inventory_hostname = {{ inventory_hostname }}"

    - name: fetch.env from /home/docker-jitsi-meet/.env
      run_once: true
      fetch:
        src: /home/docker-jitsi-meet/.env
        dest: /home/.env
        flat: true
      when: inventory_hostname == "jitsi"

    - name: Copy the file .env from master to videobridge
      copy:
        src: /home/.env
        dest: /home/docker-jitsi-meet/.env
      when: inventory_hostname == "videobridge"
