---
- hosts: jitsi
  become: true
  vars:
    docker_compose_version: "1.29.2"
  tasks:

  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=3600

  - name: Upgrade all apt packages
    apt: upgrade=dist

  - name: Install dependencies
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
      update_cache: true

  - name: Install Docker
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Add remote "root" user to "docker" group
    user:
      name: "root"
      group: docker
      append: true

  - name: Download docker-compose {{ docker_compose_version }}
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
      dest: ~/docker-compose
      mode: '+x'

  - name: Check docker-compose exists
    stat: path=~/docker-compose
    register: docker_compose

  - name: Move docker-compose to /usr/local/bin/docker-compose
    command: mv ~/docker-compose /usr/local/bin/docker-compose
    when: docker_compose.stat.exists

  - name: Creating a file with configuration 
    copy:
      dest: "/home/VideoBridges/docker-compose.yml"
      content: |
         version: '3'
         
         services:
             # Video bridge
             jvb2:
                 #image: jitsi/jvb:latest
                 build: ./jvb
                 restart: ${RESTART_POLICY}
                 ports:
                     - '${JVB_PORT}:${JVB_PORT}/udp'
                     - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
                 volumes:
                     - ${CONFIG}/jvb:/config:Z
                 environment:
                     - DOCKER_HOST_ADDRESS
                     - XMPP_AUTH_DOMAIN
                     - XMPP_INTERNAL_MUC_DOMAIN
                     - XMPP_SERVER
                     - JVB_AUTH_USER
                     - JVB_AUTH_PASSWORD
                     - JVB_BREWERY_MUC
                     - JVB_PORT
                     - JVB_TCP_HARVESTER_DISABLED
                     - JVB_TCP_PORT
                     - JVB_TCP_MAPPED_PORT
                     - JVB_STUN_SERVERS
                     - JVB_ENABLE_APIS
                     - JVB_WS_DOMAIN
                     - JVB_WS_SERVER_ID
                     - PUBLIC_URL
                     - TZ
                 #depends_on:
                 #    - prosody
                 networks:
                     meet.jitsi:
                         aliases:
                             - ${JVB_AUTH_USER}.${XMPP_DOMAIN}
                 extra_hosts:
                     - "xmpp.meet.jitsi:185.139.68.189"
